### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by iqrohan** [iquesters/turnstile#1]
Both configurations 'pic18f46k22' & 'pic16f877a' have compilation warnings.

All compilation warning are to be removed.

**Comment by noyelseth** [comment]
In pic16f877a_dip
eusart1.c:78: warning: (520) function "_EUSART1_Write" is never called
because "EUSART1_Write" function's logical part is being used in "put_string" function for print log.
Actually "EUSART1_Write" function internally called by "printf" <stdio.h> lib function. So, I make "EUSART1_Write" function un-commented, for this reason "warning: (520) function "_EUSART1_Write" is never called" shows.

But in pic18f46k22_dip
warning: (520) function "_EUSART1_Read" is never called 
because, by MCC configuration USART1's continuous read is enable. For that reason, "EUSART1_Read" function generate by MCC. And it never used. It commented this function for warning resolved.
